name: Aviation Data CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # Jalan setiap 3 jam (menit ke-0)

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Pytest
        run: pip install pytest

      - name: Run Validation Tests
        run: pytest test_data.py

      - name: Run Main Program
        run: python main.py
